### ISSUE TITLE
Új probléma

### ISSUE THREAD

**Issue by danger97** [danger97/RFT_NetBeans#1]
A regisztráció után nem irányítja át a felhasználót a fő oldalra
Kérlek nézzétek meg! @CaptainCandyyyyyy @actorvmi16

**Comment by actorvmi16** [comment]
Az aktuális probléma megoldás alatt áll. @danger97

**Comment by CaptainCandyyyyyy** [comment]
A probléma megoldódott.  @danger97 @actorvmi16

**Comment by danger97** [comment]
Lezárom a hibát, késznek nyilvánítom!
